//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.SortingServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SortingServiceReference1.ISortingService1")]
    public interface ISortingService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISortingService1/Sort", ReplyAction="http://tempuri.org/ISortingService1/SortResponse")]
        string Sort(string numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISortingService1/Sort", ReplyAction="http://tempuri.org/ISortingService1/SortResponse")]
        System.Threading.Tasks.Task<string> SortAsync(string numbers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISortingService1Channel : WebApplication1.SortingServiceReference1.ISortingService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SortingService1Client : System.ServiceModel.ClientBase<WebApplication1.SortingServiceReference1.ISortingService1>, WebApplication1.SortingServiceReference1.ISortingService1 {
        
        public SortingService1Client() {
        }
        
        public SortingService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SortingService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SortingService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SortingService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Sort(string numbers) {
            return base.Channel.Sort(numbers);
        }
        
        public System.Threading.Tasks.Task<string> SortAsync(string numbers) {
            return base.Channel.SortAsync(numbers);
        }
    }
}
